[package]
name = "cord"
version = "0.0.1"
authors = ["Placeholder crate, please do not install"]
description = "This is a placeholder crate for the Cord Project. Please do not use this crate."
license = "MPL-2.0"
