# Base image
FROM rust:alpine as builder
WORKDIR /usr/src/cord
COPY . .
RUN apk update && \
    apk upgrade && \
    apk add --update alpine-sdk && \
    cargo install --path cord-client/

# Client CLI
FROM alpine
COPY --from=builder /usr/local/cargo/bin/cord /usr/local/bin/cord
RUN apk update && apk upgrade
ENTRYPOINT ["cord"]
CMD ["--help"]
