[package]
name = "generators"
version = "0.1.0"
authors = ["Pete Hayes <pete@hayes.id.au>"]
edition = "2018"

[dependencies]
client = { path = "../client" }
futures = "0.1"
log = "0.4"
message = { path = "../message" }
pattern-matcher = { path = "../pattern-matcher" }
rand = "0.7"
tokio = "0.1"
