[package]
name = "cord-message"
version = "0.1.0"
authors = ["Pete Hayes <pete@hayes.id.au>"]
edition = "2018"

[dependencies]
bytes = "0.4"
cord-pattern = { version = "0.1", path = "../cord-pattern" }
error-chain = "0.12"
tokio-codec = "0.1"
